---
kind: pipeline
type: kubernetes
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: docker
  image: harbor.ntppool.org/ntppool/drone-kaniko:main
  pull: always
  settings:
    repo: ntppool/ntppool
    registry: harbor.ntppool.org
    tags: SHAABBREV,SHA7,${DRONE_BRANCH}
    auto_tag: true
    cache: true
    username:
      from_secret: harbor_username
    password:
      from_secret: harbor_password
---
kind: signature
hmac: 73431ff051c236556115120c88b7ce7be5a45611578ea5a695dbe779a721334b

...
